### ISSUE TITLE
Errors out when using VKDoom on startup

### ISSUE THREAD

**Issue by Underqualified-Gunman** [boogiebogus/powersuit#7]
startup Console error
![error](https://github.com/boogiebogus/powersuit/assets/5576256/88587e52-0587-4abf-8cb2-236c4ea917b0)

Line of code it references
![code](https://github.com/boogiebogus/powersuit/assets/5576256/af550c9c-431a-4047-9813-c0b23c1fbd5b)

**Comment by boogiebogus** [comment]
Fixed.
